config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html$
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end
  delete "/doses/:id", to: "doses#destroy", as: "dose"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_and_belongs_to_many :cocktails
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktails, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
      if @cocktail.save
        redirect_to cocktail_path(@cocktail)
      else
        render :new
      end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def set_cocktails
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def index
    @doses = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail_id = @cocktail.id
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail_id)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end

  # def set_doses
  #   @dose = dose.find(params[:id])
  # end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/cocktails/edit.html.erb
<h1 class ="text-center mt-3"><%= "You can edit #{@cocktail.name} info" %></h1>
<%= render 'form' %>

app/views/cocktails/index.html.erb
<h1>All cocktails</h1>


  <ul>
  <% @cocktails.each do |cocktail| %>
    <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
  <% end %>
  </ul>

 <%= link_to "Add a new cocktail" , new_cocktail_path%>

app/views/cocktails/new.html.erb
<h1 class ="text-center mt-3"><%= "You can add a new cocktail" %></h1>
<%= render 'form' %>

app/views/cocktails/show.html.erb
<h1> <%= "This is #{@cocktail.name} details" %></h1>
<br>
  <% @cocktail.doses.each do |dose| %>
    <ul>
      <li><%= dose.ingredient.name %> <%= "#{dose.description} cl"%></li>
      <%= link_to "Destroy #{dose.ingredient.name}", cocktail_dose_path(@cocktail, dose), method: :delete, data: { confirm: "Are you sure?"} %>
    </ul>
  <% end %>

<%= link_to "Edit #{@cocktail.name}'s name", edit_cocktail_path(@cocktail) %>
<br>
<%= link_to "Add a new dose", new_cocktail_dose_path(@cocktail) %>
<br>
<%= link_to "Back to all cocktails", cocktails_path %>

app/views/doses/new.html.erb
<h1>Create a new dose for <%= @cocktail.name %></h1>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit %>
<% end %>

app/views/doses/show.html.erb
<h1> <%= "This is #{@dose.description} details" %></h1>
<% @doses.each do |dose| %>
  <ul>
    <% raise %>
  <li><%= dose. %></li>
  <ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>